# Generated by Django 5.2.4 on 2025-08-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_alter_school_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.CharField(default='None', max_length=64),
            preserve_default=False,
        ),
    ]
