# Generated by Django 5.2.4 on 2025-08-08 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_school_country_school_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.CharField(default='none', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
