# Generated by Django 5.2.4 on 2025-08-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=16)),
                ('name', models.CharField(max_length=64)),
                ('votes', models.IntegerField()),
            ],
        ),
    ]
