# Generated by Django 5.2.4 on 2025-08-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ranking',
            old_name='name',
            new_name='business',
        ),
        migrations.AddField(
            model_name='ranking',
            name='school',
            field=models.CharField(default='UIUC', max_length=64),
            preserve_default=False,
        ),
    ]
