# Generated by Django 5.2.4 on 2025-08-06 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0002_rename_name_ranking_business_ranking_school'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='schools.school'),
        ),
    ]
