# Generated by Django 5.2.4 on 2025-08-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0003_alter_ranking_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ranking',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
