# Generated by Django 5.2.4 on 2025-08-08 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0004_alter_ranking_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
    ]
