# Generated by Django 5.2.4 on 2025-08-08 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0005_rankingcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranking',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='rankings.rankingcategory'),
        ),
    ]
