# Generated by Django 5.2.4 on 2025-08-08 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rankings', '0006_ranking_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='type',
        ),
    ]
